// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFESiFV0aeIJFCeIOVZLblWB9Ibe1G9vQ',
    appId: '1:465728583379:web:3a38f1b1dd649f3e92c626',
    messagingSenderId: '465728583379',
    projectId: 'smart-diet-app-fdcca',
    authDomain: 'smart-diet-app-fdcca.firebaseapp.com',
    storageBucket: 'smart-diet-app-fdcca.firebasestorage.app',
    measurementId: 'G-B825PVTERY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBexpOvhLOoUzkwNsDNABvXogKHh0aE1oM',
    appId: '1:465728583379:android:d10e4a50010c952692c626',
    messagingSenderId: '465728583379',
    projectId: 'smart-diet-app-fdcca',
    storageBucket: 'smart-diet-app-fdcca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNi4hz7YIJ-LB99vPegoc6jnI6H4qnsRs',
    appId: '1:465728583379:ios:372b965cc8a46ae492c626',
    messagingSenderId: '465728583379',
    projectId: 'smart-diet-app-fdcca',
    storageBucket: 'smart-diet-app-fdcca.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartDietApp',
  );
}
